# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160205_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsmodel',
            name='nickname',
            field=models.TextField(default='', help_text='this is stupid. max 50 characters', max_length=50),
            preserve_default=False,
        ),
    ]
