# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_detailsmodel_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsmodel',
            name='nickname',
            field=models.TextField(blank=True, help_text='this is stupid. max 50 characters', max_length=50, null=True),
        ),
    ]
