# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20160206_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsmodel',
            name='rather_nots',
            field=models.TextField(blank=True, help_text='Dingen die je liever niet wil eten.', null=True),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='allergies',
            field=models.TextField(blank=True, help_text='Dingen waarvoor je allergies bent. Zet hier AUB alleen maar serieuze dingen bij.', null=True),
        ),
        migrations.AlterField(
            model_name='detailsmodel',
            name='nickname',
            field=models.TextField(blank=True, help_text='this is stupid. max 50 characters.', max_length=50, null=True),
        ),
    ]
