# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20160210_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsmodel',
            name='nickname',
            field=models.CharField(blank=True, help_text='this is stupid. max 50 characters.', max_length=50, null=True),
        ),
    ]
