# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=300)),
                ('title_slug', models.CharField(blank=True, max_length=300, null=True)),
                ('date_last_edited', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField(help_text='Markdown is enabled')),
            ],
            options={
                'ordering': ('-date_posted', '-date_last_edited'),
            },
        ),
    ]
