# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievementget',
            options={'ordering': ('-score',)},
        ),
        migrations.AddField(
            model_name='achievement',
            name='related_image',
            field=models.ImageField(default='', upload_to='%y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievementget',
            name='score',
            field=models.IntegerField(),
        ),
    ]
