# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20160329_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='related_image',
            field=models.FileField(upload_to='media/1%y/%m/%d'),
        ),
    ]
