# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_auto_20160329_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='related_image',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='date_created',
            field=models.DateTimeField(auto_now=True, help_text='datum aangemaakt'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='date_last_accessed',
            field=models.DateTimeField(help_text='Datum waarop de achievement voor het laatst verander was'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(help_text='Beschrijving van de achievements'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(help_text='Naam van de achievement', max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name_slug',
            field=models.CharField(blank=True, help_text='slug van de naam. Vul dit niet in', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementget',
            name='achievement',
            field=models.ForeignKey(help_text='Achievement die is gehaald', on_delete=django.db.models.deletion.CASCADE, to='achievements.Achievement'),
        ),
        migrations.AlterField(
            model_name='achievementget',
            name='awarded_by',
            field=models.ForeignKey(help_text='Lid van de ZG die de achievement heeft uitgedeeld', on_delete=django.db.models.deletion.CASCADE, related_name='awarded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='achievementget',
            name='date_achieved',
            field=models.DateTimeField(auto_now=True, help_text='datum aangemaakt'),
        ),
        migrations.AlterField(
            model_name='achievementget',
            name='score',
            field=models.IntegerField(help_text='Score die is gehaald voor de achievement'),
        ),
        migrations.AlterField(
            model_name='achievementget',
            name='user',
            field=models.ForeignKey(help_text='Gebruiker die een Achievement heeft gehaald', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achievement',
            name='related_game',
            field=models.ForeignKey(default='', help_text='Spel waar de achievement bij hoort', on_delete=django.db.models.deletion.CASCADE, to='achievements.Game'),
            preserve_default=False,
        ),
    ]
