# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_auto_20160330_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='date_last_accessed',
            field=models.DateTimeField(blank=True, help_text='Datum waarop de achievement voor het laatst verander was', null=True),
        ),
        migrations.AlterField(
            model_name='achievementget',
            name='score',
            field=models.IntegerField(blank=True, default=-1, help_text='Score die is gehaald voor de achievement', null=True),
        ),
    ]
