# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dining', '0004_auto_20160205_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningparticipation',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
