# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0006_diningcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningcomment',
            name='dining_list',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dining.DiningList'),
            preserve_default=False,
        ),
    ]
