# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining', '0007_diningcomment_dining_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningcomment',
            name='date_posted',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 15, 15, 5, 32, 747709)),
            preserve_default=False,
        ),
    ]
